name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: >
        sudo apt-get update;
        sudo apt-get install -yq
        python3-msgpack
        python3-numpy

    - name: Test
      run: python3 test.py
